# Project configuration

project:
  name: CI Medical Diagnosis MVP
  seed: 42

paths:
  raw_data_dir: "dataset/archive/PTB diagnostic ecg database csv files"
  processed_dir: data/processed
  cache_dir: .cache

# Temporal windowing
window:
  seconds: 10
  overlap_fraction: 0.5
  pad_mode: reflect

# Spectrogram parameters (STFT)
spectrogram:
  n_fft: 512
  hop_length: 128
  win_length: 512
  power: 2.0
  mel_scale: false
  n_mels: 128
  normalize: zscore

# Feature extractor
model:
  backbone: resnet18
  embedding_dim: 512
  pretrained: true
  finetune_last_block: false

# Data loading
loader:
  dataset: csv
  timestamp_column: time
  value_column: value
  sampling_rate_hz: 360
  file_glob: "**/*.csv"

# Label mapping (external YAML)
labels:
  mapping_file: configs/labels_pnc.yaml
  default_class: Unknown

# Runtime
runtime:
  num_workers: 4
  batch_size: 32
